/** Visible strings for the cut view. Sentence case, no dashes. */
export const timelineCopy = {
  header: {
    clipsRendered: (rendered: number, total: number) =>
      `${rendered}/${total} clips rendered`,
    exportBoard: "Export contact sheet",
    exportCut: "Export cut data",
    exportFailed: "Export failed.",
  },
  stage: {
    frameAlt: (shotNumber: number) => `Frame for shot ${shotNumber}`,
    slateFallback: (shotNumber: number) => `Shot ${shotNumber}`,
  },
  transport: {
    previous: "Previous shot",
    next: "Next shot",
    play: "Play",
    pause: "Pause",
    shotOf: (current: number, total: number) => `shot ${current} / ${total}`,
    mute: "Mute clip audio",
    unmute: "Unmute clip audio",
  },
  filmstrip: {
    label: "Filmstrip",
    goToShot: (shotNumber: number) => `Go to shot ${shotNumber}`,
  },
  exporter: {
    nothingToExport: "There are no shots to export yet.",
  },
  lanes: {
    title: "Audio",
    dialogueLane: "Dialogue",
    musicLane: "Music",
    ambienceLane: "Ambience",
    dialogueEmpty:
      "No shots carry dialogue. Add lines in the storyboard and they appear here.",
    laneEmpty: "No tracks yet. Add one and describe what it should sound like.",
    generate: "Generate",
    regenerate: "Regenerate",
    generationFailed: "Generation failed.",
    dialogueTask: (shotNumber: number) => `Dialogue, shot ${shotNumber}`,
    playDialogue: (shotNumber: number) => `Play dialogue for shot ${shotNumber}`,
    stopDialogue: (shotNumber: number) => `Stop dialogue for shot ${shotNumber}`,
    voiceOf: (name: string) => `Voice: ${name}`,
    noVoice: "Default voice",
    addMusic: "Add music",
    addAmbience: "Add ambience",
    musicTask: "Music track",
    ambienceTask: "Ambience track",
    musicPromptLabel: "Music prompt",
    ambiencePromptLabel: "Ambience prompt",
    musicPromptPlaceholder: "Slow piano under a night drive",
    ambiencePromptPlaceholder: "Rain on a tin roof, distant thunder",
    gainLabel: "Gain",
    mute: "Mute track",
    unmute: "Unmute track",
    removeTrack: "Remove track",
    levelLabel: "Level",
  },
  render: {
    title: "Render",
    hint: "Renders every shot with burned captions and the audio mix into one file.",
    start: "Render final cut",
    cancel: "Cancel render",
    frameOf: (frame: number, total: number) => `frame ${frame} / ${total}`,
    failed: "Render failed.",
    retry: "Retry",
    doneLabel: (container: string, height: number) =>
      `Final cut (${container}, ${height}p)`,
    assetLabel: "Final cut render",
    download: "Download",
    saveToAssets: "Save to assets",
    savedToAssets: "Saved to assets",
    playerTitle: "Final cut preview",
  },
  empty: {
    title: "Nothing on the timeline",
    hint: "The cut assembles every shot in script order. Write scenes and break them into shots first.",
    action: "Go to script",
  },
} as const;
