/** Every visible string in the previz view, per the build charter. */
export const previzCopy = {
  empty: {
    title: "No shots to block",
    hint: "Previz stages a shot in 3d before framing. Break scenes into shots on the board, then block the camera here.",
    action: "Open the board",
  },
  rail: {
    label: "Shots",
    noShots: "No shots yet.",
    noDescription: "No description yet",
  },
  stage: {
    webglFailedTitle: "3d viewport unavailable",
    webglFailedHint:
      "WebGL could not start in this browser, and previz needs it to draw the stage.",
    retry: "Retry",
    modeLabel: "Stage mode",
    modeBlocking: "Blocking",
    modeCamera: "Camera",
    scrubLabel: "Scrub",
    scrubTime: (current: string, total: string) => `${current}s / ${total}s`,
    blockingHint: "Drag mannequins and props on the floor. Drag empty space to orbit.",
    cameraHint: "Drag to orbit the active keyframe around its look target. Scroll to dolly.",
    saveFailed: "The blockout could not be saved locally.",
  },
  blocking: {
    title: "Set dressing",
    copyFromPrevious: "Copy blocking from previous shot",
    copyFromPreviousHelper:
      "Copies mannequin and prop positions from the previous shot in this scene. The camera stays on this shot's own preset.",
    copyFromPreviousUnavailable:
      "Block the previous shot in this scene first to copy from it here.",
    castLabel: "Cast",
    noCast: "No characters in this shot. Attach them on the board.",
    propsLabel: "Props",
    propKindLabel: "Prop kind",
    propKinds: {
      box: "Box",
      cylinder: "Cylinder",
      plane: "Wall",
    },
    addProp: "Add prop",
    selectionLabel: "Selection",
    nothingSelected: "Click a mannequin or prop in the viewport to select it.",
    rotationLabel: "Rotation",
    removeProp: "Remove prop",
  },
  camera: {
    title: "Camera",
    presetLabel: "Move preset",
    presetHelper: "Changing the preset reseeds both keyframes.",
    reseed: "Reseed keyframes",
    keyframeLabel: "Keyframe",
    keyframeA: "A",
    keyframeB: "B",
    positionLabel: "Position",
    lookAtLabel: "Look at",
    focalLabel: "Focal length",
    focalValue: (focal: number) => `${focal}mm`,
    axis: { x: "x", y: "y", z: "z" },
  },
  capture: {
    title: "Capture",
    capture: "Capture previz",
    recapture: "Recapture",
    idleHint: "No previz clip yet. Capture renders the camera move as a clay pass.",
    statusIdle: "Ready to capture",
    statusClay: (percent: number) => `Rendering clay pass ${percent}%`,
    statusDepth: (percent: number) => `Rendering depth pass ${percent}%`,
    statusSaving: "Saving clip",
    statusDone: (codec: string) => `Capture complete, ${codec}`,
    statusFailed: (message: string) => `Capture failed. ${message}`,
    retry: "Retry",
    replay: "Replay",
    downloadDepth: "Download depth pass",
    clipAlt: (shotNumber: number) => `Previz clip for shot ${shotNumber}`,
    meta: (seconds: number) => `${seconds}s at 12 fps, 640x360`,
    saveFailed: "The clip could not be saved to the asset library.",
    assetPrompt: (presetLabel: string) => `Previz clay pass, ${presetLabel}`,
  },
} as const;
